### ISSUE TITLE
Contribution terms unclear

### ISSUE THREAD

**Issue by funnelfiasco** [red-hat-people-team/open-decision-framework#15]
Do contributors assign copyright to Red Hat? (Please say no.) I'd propose updating the README to include a statement that contributions are accepted under CC BY-SA 4.0 (i.e. inbound == outbound), and changing copyright statements to saying Red Hat and contributors.

I was going to start on a PR for this, but decided I should wait until I had guidance that this is acceptable.

**Comment by ruhbehka** [comment]
To be honest, I find the CC / copyright terms a bit confusing. My understanding from conversations with @semirobotic is that to release something under CC, someone has to hold the copyright (kind of a benevolent holder?). How it works beyond that is unclear to me.

I'm assuming that CC-BY-SA means you are obligated to release a fork under the same license (that's the SA part) and attribute it to the upstream one you worked from (the BY part).

How all of this works with contributions from others back upstream gets even more confusing to me. (I used the same wording @jhibbets and @semirobotic used for the Open Org Field Guide, because it has multiple contributors and seemed a good model to apply.)

**Comment by ruhbehka** [comment]
@semioticrobotic rather!

**Comment by funnelfiasco** [comment]
Right, you need to have the copyright to attach a license to a work. So when someone makes a contribution to this repo, there are two options effectively:

1. The author assigns the copyright in their contribution to Red Hat
2. The author contributes their work under a license that allows Red Hat (or other downstreams) to distribute it under the CC BY-SA licensed used for the larger work. In practice, this is often done as "inbound equals outbound". In other words: the license the finished work is distributed under is the license that contributors agree to contribute under.

I'd be happy to discuss this in person tomorrow afternoon or some other time that's convenient for you.

**Comment by lintqueen** [comment]
I wrote a whole long thing about CLAs and stuff, but having re-and-re-and-re-read this...

@ruhbehka You are right, you have to *have* copyright to assign a license; however, all creative works are considered copyrighted when fixed in a medium.  So, even this little text message is copyrighted.  

So I think what @funnelfiasco is getting at is: his stuff is copyright him (period); however, Red Hat *could* (but probably shouldn't) require he assign that copyright to *us* before we incorporate his work (that'd be like a CLA, or Contributor License Agreement).  The other option is that he retains his copyright (as we retain ours), but his contributions (+ the original material) would create a new, derivative work, which (because it's CC-BY-SA) would also be CC-BY-SA.  But we aren't *explicitly* saying that anywhere, which we probably should. 

I think this is the relevant stuff from opensource.com, which covers both Red Hat's rights _and_  the author's:

"Red Hat License to You. Red Hat either owns the copyright in the HTML, text, images, audio, video, software or other content that is made available on the Website, has used reasonable efforts to obtain permission of the owner of the copyright to make it available on this Website, or has otherwise determined that the content is available for use on the Website. For Red Hat original content on the Website, Red Hat licenses the content under the terms of the Creative Commons Attribution-ShareAlike 4.0 International license ("CC-BY-SA") with the following exceptions: (1) no license is granted for use of the Marks; (2) no license is granted for use of the Drupal theme of the Website; (3) no license is granted for content identified on the Website as not available under CC BY-SA 4.0 or content identified as available under terms different from CC BY-SA 4.0. Such identification may be, by way of example, notification of license terms other than CC BY-SA 4.0, or a statement reserving all rights in the content. Red Hat will use reasonable efforts to ensure that the copyright owner of the content it provides, if known, is clearly identified, but does not represent or warrant that any content it provides is noninfringing or available under CC BY-SA 4.0 or any other license. You are responsible for ensuring that Your reuse of content from this Website is lawful. 

For Red Hat original content, for purposes of attribution under CC BY-SA 4.0 please use the following statement: "By [author's screen name] from Opensource.com" and include a permanent link to the content.

Your License to Red Hat and Other Users. By displaying, publishing or making available any content, messages, text, files, images, photos, video, sounds, profiles, **works of authorship or any other materials, You represent and warrant that the content does not and will not defame any person or entity, or violate or infringe upon the copyright, trademark, patent, trade secret, right of privacy, right of publicity, or other right of any person, that the content is available for licensing under the terms You designate (if any), or else is available under terms not incompatible with CC BY-SA 4.0, that You are hereby licensing the content under the terms of CC BY-SA 4.0 (or under such other license that You designate), and, if You designate a Creative Commons license earlier than the Creative Commons 4.0 license series as applicable to Your content, that You expressly waive (to the extent such rights are waivable) all moral rights, droit moral or similar rights that, if enforced, would prevent the full use of the works as contemplated under the terms of the designated license. "**

****I do not claim to know much about anything, especially intellectual property.  But this interests me, so I took a stab at trying to understand it.  Am looking forward to finding out if I'm wwwaaaaaaayyyy off..*****

**Comment by funnelfiasco** [comment]
@lintqueen yeah, you nailed what I'm getting at.

Maybe it would be easiest if I went ahead and wrote what I'd like to see so that we have a specific target to work on.

**Comment by ruhbehka** [comment]
If you have time to work something up, that would be great. Otherwise, I'll reach out to our Legal team to get advice on how to word it. Thanks!

**Comment by funnelfiasco** [comment]
@ruhbehka I opened a pull request (#15) which I hope makes it more clear what I'm trying to accomplish. I don't think it changes anything of substance, it just clarifies what (I assume) is the intent in opening this up for community contribution.
