### ISSUE TITLE
GitHub Markdown rendering differently

### ISSUE THREAD

**Issue by ruhbehka** [red-hat-people-team/open-decision-framework#23]
Hi all,
GitHub seems to have tightened up their Markdown rendering specs, and now some of our Markdown pages aren't formatting properly. If anyone has Markdown skills and can help sort out this issue, I'd appreciate the help. I think the anchors are what's breaking things, but I can't seem to find a way to make it work properly.

Example - see the "Overview" section on this page: 
https://github.com/red-hat-people-team/open-decision-framework/blob/master/ODF-community.md

**Comment by daamien** [comment]
I think you just needs to put an blank line before the title.

For instance in the  following section:

```
<br/>
Overview<a name="overview"></a>
===========================================================================
_page 2 of 15_
````
You simple add a line between `<br/>` and `Overview`

```
<br/>

Overview<a name="overview"></a>
===========================================================================
_page 2 of 15_
````

**Comment by daamien** [comment]
Also the `<br/>` tags seem useless to me because if you want to force a line break in a document, you can do it with a blank line

see https://help.github.com/articles/basic-writing-and-formatting-syntax/#paragraphs-and-line-breaks

Also the `<a name="overview"></a>` tag is redundant because github will automatically create the so-called "section links" for each title and subtitle

see https://help.github.com/articles/basic-writing-and-formatting-syntax/#section-links

**Comment by ruhbehka** [comment]
Excellent - fixed all. Working on the French version now as well. :) Thanks!
